### ISSUE TITLE
Self-Contained app and "Move" shapes button

### ISSUE THREAD

**Issue by mauriva** [mohammadKarimi/Riter#151]
I really appreciate that Riter is in portable mode, which is very useful for me.
I would like to be able to use it on a PC where I don't have administrator privileges and can't install anything. However, Riter requires Windows Desktop Runtime to function, which I can't install on those PCs.
Is there a way to create a portable version that can be run on a Windows PC even if the Runtime is not installed?

Regarding the program's features, I am requesting one that seems to be missing at the moment. Once something is drawn (for example, a line), I would like there to be a "Move" mode that allows you to drag and move what has been drawn.

Than you!

**Comment by mohammadKarimi** [comment]
@mauriva Move Options is live now. 
for Self-Contained app, could you please add another issue.
