### ISSUE TITLE
Collapse All Toolbox When Hidden Button Clicked

### ISSUE THREAD

**Issue by hassan-hamidi** [mohammadKarimi/Riter#179]
When the "HideAll" button is clicked, all tools except "EnableTimer" are hidden. Since that tool is also useless in this mode, I think it is better to hide both "EnableTimer" and automatically switch to the Release tool.

**Comment by mohammadKarimi** [comment]
It is Live now.

**Comment by hassan-hamidi** [comment]
thanks.
