### ISSUE TITLE
Add Option For EnableTimer

### ISSUE THREAD

**Issue by hassan-hamidi** [mohammadKarimi/Riter#182]
Adding the Enable timer option is a very interesting idea and I suggest giving the user the ability to manage that time. 
For example, they can change the display time between 0.5 and 5 seconds.

**Comment by mohammadKarimi** [comment]
Thanks, I will add a new overlay panel, then user can change the time of fading.

**Comment by mohammadKarimi** [comment]
it is live now. thanks for your feature.
