### ISSUE TITLE
Global hotkeys (With Code)

### ISSUE THREAD

**Issue by mohammadKarimi** [mohammadKarimi/Riter#3]
A global hotkey would be useful for enabling/disabling the app whether its in focus or not

**Comment by MohammadMokhtarii** [comment]
Could you provide more details about it? I'm eager to implement it.
@mohammadKarimi

**Comment by mohammadKarimi** [comment]
A global hotkey would be useful for enabling/disabling the app whether its in focus or not.
something like this: 
```

 [DllImport("user32.dll")]
        private static extern bool RegisterHotKey(IntPtr hWnd, int id, uint fsModifiers, uint vk);

        [DllImport("user32.dll")]
        private static extern bool UnregisterHotKey(IntPtr hWnd, int id);

        private IntPtr windowHandle;
        private HwndSource source;
```

**Comment by MohammadMokhtarii** [comment]
What are your desired hotkeys and related functionality?
