### ISSUE TITLE
Send HotKeys to View Model to Handle which Action must call.

### ISSUE THREAD

**Issue by mohammadKarimi** [mohammadKarimi/Riter#38]
After adding the HotKeys (static for now) in a dictionary like [R] for Release button. now we want to send this hotkey to View Model to decide which method must be called.

**Comment by mohammadKarimi** [comment]
@MohammadMokhtarii you can now add this feature.

**Comment by MohammadMokhtarii** [comment]
#40 is the desired implementation.
