### ISSUE TITLE
The issue of the keyboard not working during program execution

### ISSUE THREAD

**Issue by NimaKaviyani** [mohammadKarimi/Riter#86]
When I open the program, even after changing the shortkey buttons, some of the keyboard keys do not work. For example: _D_ and _E_.

**Comment by mohammadKarimi** [comment]
we have to change this code to revert key listener from OS to app focused.

**Comment by mohammadKarimi** [comment]
Instead of using RegisterHotKey, we can use a global keyboard hook to listen for key events. This way, we can monitor key presses without intercepting them and can choose whether to handle them or allow them to pass through to other applications.
